#!/bin/sh

host=`hostname`
directory=$1
code=$2
metric="quick-dirty-sloc $host:$directory"
unit="lines of code"
if [ "$3" != "" ]; then
    url=$3
else
    url="http://localhost:8080/metric"
    #url="https://level-up.appspot.com/metric"
fi

count=`sloccount $directory | \
       awk '/^Total Physical Source/ { print gensub(",","","g",$9) }'`
curl -F 'code='"$code" \
     -F 'metric='"$metric" \
     -F "value=$count" -F "unit=$unit" $url
