application: level-up
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /me/metric.*
  login: required
  script: metric.py

- url: /metric
  secure: always
  script: metric.py

- url: /me.*
  login: required
  script: me.py

- url: /view
  login: required
  script: me.py

- url: /.*
  script: main.py

