application: level-up
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /me/metrics
  login: required
  script: metric.py

- url: /me/metrics/.*
  login: required
  script: metric.py

- url: /me
  login: required
  script: me.py

- url: /me/.*
  login: required
  script: me.py

- url: /metric
  secure: always
  script: metric.py

- url: /.*
  script: main.py

